name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.0.5
publish_to: 'none'
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  lottie:
  # services
  video_player:
    git:
      url: https://github.com/ghondar/plugins.git
      ref: main
      path: packages/video_player/video_player
  http:
  get:
  wakelock:
  universal_html:
  youtube_explode_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/
